server:
  port: 8080
spring:
  application:
    name: "authentication-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    host: ${R2DBC_HOST_AUTH:localhost}
    port: "3306"
    username: ${CREDI_USER_DB}
    password: ${CREDI_PASS_DB}
    database: "authentication-db"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    root: INFO
    co.com.pragma: TRACE

routes:
  paths:
    users: "/api/v1/usuarios"
    usersByDocumentId: "/api/v1/usuarios/{idDocument}"
    login: "api/v1/login"
    usersByEmails: "/api/v1/usuarios/emails"

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

whitelist:
  paths:
    - "/v3/api-docs"
    - "/actuator/health"
    - "/actuator/info"
    - "/swagger-ui/index.html"
    - ${routes.paths.login}

